# Generated by Django 4.1.2 on 2022-11-11 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PatientsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(choices=[('CHILD', 'CHILD'), ('ADULT', 'ADULT')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('sur_name', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('charge', models.PositiveIntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('ORTHOPEDIC DOCTOR', 'ORTHOPEDIC DOCTOR'), ('PHYSICIAN', 'PHYSCICIAN'), ('LAB TECH', 'LAB TECH'), ('RECEPTIONIST', 'RECEPTIONIST'), ('NURSE', 'NURSE'), ('ACCOUNTS', 'ACCOUNTS'), ('PHARMACIST', 'PHARMACIST')], max_length=30)),
                ('first_name', models.CharField(max_length=50)),
                ('sur_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.departmentsmodel')),
            ],
        ),
    ]
