# Generated by Django 4.1.3 on 2022-11-12 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ChargesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptartment', models.ManyToManyField(to='mainapp.departmentsmodel')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.patientsmodel')),
                ('service', models.ManyToManyField(to='mainapp.servicesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_results', models.TextField(blank=True)),
                ('mini_lab_results', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.patientsmodel')),
                ('prescription_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.usersmodel')),
            ],
            options={
                'unique_together': {('patient_id', 'prescription_by')},
            },
        ),
    ]
