# Generated by Django 4.1.3 on 2022-11-14 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_usersmodel_available_chargesmodel_patientdoctormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.patientsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('prescription', models.TextField(blank=True, max_length=1000)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.departmentsmodel')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.patientsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LabModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('upload', models.CharField(blank=True, max_length=300)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.departmentsmodel')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.patientsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MiniLabModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('upload', models.CharField(blank=True, max_length=300)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.departmentsmodel')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.patientsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.departmentsmodel')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.patientsmodel')),
                ('services', models.ManyToManyField(to='mainapp.servicesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='XrayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('upload', models.CharField(blank=True, max_length=300)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.departmentsmodel')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.patientsmodel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='patientdoctormodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='patientdoctormodel',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='patientdoctormodel',
            name='prescription_by',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='available',
        ),
        migrations.DeleteModel(
            name='ChargesModel',
        ),
        migrations.DeleteModel(
            name='PatientDoctorModel',
        ),
    ]
