# Generated by Django 4.1.3 on 2022-11-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_accountsmodel_doctormodel_labmodel_minilabmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsmodel',
            old_name='contact_no',
            new_name='patient_no',
        ),
        migrations.AddField(
            model_name='patientsmodel',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientsmodel',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='OTHER', max_length=10),
        ),
        migrations.AddField(
            model_name='patientsmodel',
            name='guardian_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patientsmodel',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='usertype',
            field=models.CharField(choices=[('ORTHOPEDIC DOCTOR', 'ORTHOPEDIC DOCTOR'), ('PHYSICIAN', 'PHYSCICIAN'), ('LAB TECH', 'LAB TECH'), ('RECEPTIONIST', 'RECEPTIONIST'), ('NURSE', 'NURSE'), ('ACCOUNTS', 'ACCOUNTS'), ('PHARMACIST', 'PHARMACIST'), ('INTERN', 'INTERN')], max_length=30),
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.departmentsmodel')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usersmodel')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.patientsmodel')),
            ],
        ),
    ]
