# Generated by Django 4.1.3 on 2022-11-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_contact_no_patientsmodel_patient_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
