# Generated by Django 4.1.3 on 2022-11-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_usersmodel_options_alter_usersmodel_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usersmodel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='sur_name',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='user_first_name',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='user_password',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
