# Generated by Django 4.1.3 on 2022-11-15 13:36

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_usersmodel_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usersmodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
