# Generated by Django 4.1.3 on 2022-11-16 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_rename_patient_id_accountsmodel_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.departmentsmodel'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.patientsmodel'),
        ),
    ]
