# Generated by Django 4.1.3 on 2022-11-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_appointmentmodel_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='doctor',
        ),
    ]
