# Generated by Django 4.1.3 on 2022-11-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_appointmentmodel_doctor'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usersmodel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='usertype',
            field=models.CharField(choices=[('ORTHOPEDIC DOCTOR', 'ORTHOPEDIC DOCTOR'), ('PHYSICIAN', 'PHYSCICIAN'), ('LAB TECH', 'LAB TECH'), ('RECEPTIONIST', 'RECEPTIONIST'), ('NURSE', 'NURSE'), ('ACCOUNTS', 'ACCOUNTS'), ('PHARMACIST', 'PHARMACIST'), ('INTERN', 'INTERN'), ('ADMIN', 'ADMIN')], max_length=30),
        ),
    ]
