# Generated by Django 4.1.3 on 2022-11-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_usersmodel_managers_remove_usersmodel_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='usertype',
            field=models.CharField(choices=[('ORTHOPEDIC DOCTOR', 'ORTHOPEDIC DOCTOR'), ('PHYSICIAN', 'PHYSCICIAN'), ('LAB TECH', 'LAB TECH'), ('RECEPTIONIST', 'RECEPTIONIST'), ('NURSE', 'NURSE'), ('ACCOUNTS', 'ACCOUNTS'), ('PHARMACIST', 'PHARMACIST'), ('INTERN', 'INTERN'), ('ADMIN', 'ADMIN'), ('USER', 'USER')], max_length=30),
        ),
    ]
