# Generated by Django 4.1.2 on 2022-11-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_usersmodel_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.receptionmodel'),
        ),
    ]
