# Generated by Django 4.1.2 on 2022-11-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_nursemodel_orthopedmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentsmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
