# Generated by Django 4.1.2 on 2022-11-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_departmentsmodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmodel',
            name='upload',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
